<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <h1>TÉRMINOS Y CONDICIONES PROPERATI</h1>
    <p>Este documento describe los términos y condiciones generales (en adelante los "Términos y Condiciones") mediante los cuales, OLX B.V., sociedad constituida bajo las leyes del Reino de los Países Bajos (en adelante, “El Administrador”), con domicilio en Taurusavenue 105, 2132 LS Hoofddorp, ofrece una serie de recursos en línea que incluye avisos clasificados y diferentes servicios de comunicación (en adelante, "los Servicios") ofrecidos dentro del sitio www.properati.com y otros dominios relacionados en donde éstos Términos y Condiciones se encuentren ("Properati" o el "sitio”), así como la política de privacidad (en adelante las “Políticas de Privacidad”) que regulan específicamente el acceso, uso e interacción del sitio.
    
    Cualquier persona que desee acceder y/o usar el sitio o los servicios podrá hacerlo, entendiéndose que al hacerlo adquiere la calidad de Usuario y está sujetándose a estos Términos y Condiciones, junto con todas las demás políticas y principios que rigen Properati y que son incorporados al presente por referencia directa o indirecta. En consecuencia, todas las visitas que se realicen a este sitio, como asimismo sus efectos jurídicos, quedarán regidos por estas reglas y sometidos a la legislación aplicable en el Reino de los Países Bajos.
    
    Los términos y condiciones contenidos en este instrumento se aplicarán y se entenderán como formando parte de todos los actos que se ejecuten en este sitio web. CUALQUIER PERSONA QUE NO ACEPTE ESTOS TÉRMINOS Y CONDICIONES, LOS CUALES TIENEN UN CARÁCTER OBLIGATORIO Y VINCULANTE, DEBERÁ ABSTENERSE DE UTILIZAR EL SITIO Y/O LOS SERVICIOS.
    
    El Usuario debe leer, entender y aceptar todas las condiciones establecidas en los Términos y Condiciones y en las Políticas de Privacidad de Properati, disponibles más abajo, así como en los demás documentos incorporados a los mismos por referencia, previo a su registración como Usuario de Properati y/o entrega de cualquier dato con cualquier fin y/o uso de cualquier Servicio. Los usuarios que deseen obtener prestaciones superiores a las básicas y gratuitas disponibles en el sitio deberán, eventualmente, tener que aceptar términos y condiciones adicionales y particulares a dichos fines. El Administrador se reserva el derecho de modificar dichos lineamientos en forma oportuna. En caso de que el Usuario no esté de acuerdo con alguna de las Condiciones, algún lineamiento o una de sus modificaciones; o bien, no esté satisfecho con Properati por cualquier motivo, el Usuario podrá dejar de usar el sitio en forma inmediata. El Administrador se reserva el derecho de actualizar las presentes Condiciones en cualquier momento. El Usuario entiende y conviene en que es el único responsable de revisar las Condiciones periódicamente. El Administrador podrá notificar aquellas modificaciones a las Condiciones que sean de mayor importancia mediante la publicación dicha notificación de modificación en el sitio, sin que esto implique obligación alguna de publicación de modificaciones. Si utiliza este Sitio significa que ha aceptado plenamente las condiciones establecidas en los Términos y Condiciones y en las Políticas de Privacidad, y por ello, se obliga a cumplir expresamente con las mismas.
    
    OBJETO
    Properati es un sitio web que facilita a los Usuarios el acceso y la utilización de diversos servicios y contenidos relacionados con la búsqueda de inmuebles, exhibiendo ofertas de ventas y/o alquileres de bienes raíces, suministrados por empresas constructoras, inmobiliarias, intermediarias y/o relacionadas con los servicios de oferta pública de inmuebles para su venta y/o alquiler. Asimismo, particulares podrán incorporar información y promocionar inmuebles de su propiedad.
    
    CAPACIDAD
    Los Servicios ofrecidos por Properati sólo están disponibles para personas que tengan capacidad legal para contratar. No podrán utilizar los servicios las personas que no tengan esa capacidad y los menores de edad. Los actos que éstos realicen en este sitio serán responsabilidad de sus padres, tutores, encargados o curadores, y por tanto se considerarán realizados por éstos en ejercicio de la representación legal con la que cuentan.
    
    CONDICIONES DE ACCESO
    El acceso al sitio atribuye al ingresante la condición de “Usuario” del mismo. El acceso a determinadas funciones de Properati requiere la identificación del Usuario mediante el llenado del formulario de registro en todos sus campos válidos y obligatorios, con información personal exacta, precisa y verdadera (“Datos Personales”), la cual el Usuario debe mantener actualizada conforme resulte necesario. Es responsabilidad exclusiva del Usuario la veracidad, exactitud, vigencia y actualización de los Datos Personales ingresados.
    
    El Usuario que complete el formulario de registro es considerado como Usuario Registrado. El Administrador se reserva el derecho de modificar los formularios de registro, debiendo los usuarios adecuar la información proporcionada por ellos a todo momento que le sea requerido. Asimismo, Properati se reserva el derecho de solicitar comprobantes y/o información adicional a los efectos de corroborar la veracidad, exactitud, vigencia y actualización de los Datos Personales sin que por esto asuma obligación alguna de hacerlo o de garantizar la titularidad o veracidad de la información subida en el sitio, pudiendo suspender, temporal o definitivamente, aquellos Usuarios cuyos datos no hayan podido ser comprobados. La registración no es requisito para el acceso al sitio y sus funciones básicas, reservándose Properati la voluntad de modificar sin necesidad de notificación previa de ningún tipo, que funciones quedan abiertas al acceso sin registración y cuales son exclusivas para los usuarios registrados. El Usuario que no completa el formulario de registro y accede al sitio, será considerado como Usuario Libre.
    
    USO DE LA CUENTA: El Usuario, registrado o libre, será responsable por todos los usos que le dé al sitio y, en su caso, a su cuenta, pues el acceso para los Usuarios Registrados está restringido al ingreso y uso de su Clave Secreta, de conocimiento exclusivo del Usuario Registrado.
    
    El Usuario se compromete a notificar a Properati en forma inmediata y por medio idóneo y fehaciente, cualquier uso no autorizado de su Cuenta, así como el ingreso por terceros no autorizados a la misma. Se aclara que está prohibida la venta, cesión o transferencia de la Clave bajo ningún título.
    
    El Usuario reconoce que los elementos, utilidades y materiales integrados dentro del sitio de Properati están protegidos por la legislación sobre derechos de autor. En consecuencia, el Usuario se compromete a respetar estos Términos y Condiciones, siendo el único responsable de su incumplimiento frente a Terceros, haciéndose en consecuencia penal, civil y administrativamente responsable por dicha acción antijurídica.
    
    El Usuario reconoce que la reproducción, copia, modificación, distribución, comercialización, descompilación, desensamblado, utilización de técnicas de ingeniería inversa o de cualquier otro medio para obtener el código fuente, transformación o publicación de cualquier resultado de pruebas de referencias no autorizadas de cualquiera de los elementos, utilidades y productos integrados y ofrecidos dentro del sitio de Properati constituye una infracción de los derechos de propiedad intelectual, obligándose, en consecuencia, a no realizar ninguna de las acciones mencionadas o cualquier otra que de cualquier manera pudiera infringir los derechos de propiedad intelectual de Properati o de terceros. El usuario entiende y conviene en que el envío de publicidad no solicitada a las direcciones de email de El Administrador o a través de los sistemas de comunicación habilitados de Properati queda expresamente prohibido por lo dispuesto en estas Condiciones. Todo uso no autorizado de los sistemas de computación de Properati representa una violación a estas Condiciones y a ciertas leyes. Dichas violaciones pueden someter al remitente o a sus representantes a multas civiles y penales.
    
    El Usuario entiende que Properati no publica ni ofrece ningún inmueble propio, sino que acerca ofertas de venta y alquiler previamente concedidas por sus respectivos propietarios y/o autorizados a empresas del sector inmobiliario, quienes, a su vez, facultan, directamente o a través de sitios web del mercado, a Properati a publicar sus ofertas.
    
    Por lo tanto, el Usuario entiende que Properati no será responsable por ninguna oferta y/o aviso que pudiera aparecer como resultado del uso del sitio. El Usuario se obliga a no utilizar el sitio de Properati para realizar o sugerir actividades prohibidas por la ley, contrarias a la moral o a las buenas costumbres.
    
    El Usuario se abstendrá de llevar a cabo cualquier conducta en el uso del sitio de Properati que atente contra los derechos de propiedad intelectual o industrial de Properati y/o de terceros, o que vulnere o transgreda el honor, la intimidad personal o familiar o la imagen de terceros, o que sean ilícitos o atenten a la moralidad, y dejará en todo caso indemne a Properati frente a cualquier reclamo, judicial o extrajudicial que se presente frente a estos como consecuencia de dicho uso.
    
    El Usuario se abstendrá de llevar a cabo por medio del uso del sitio cualquier destrucción, alteración, inutilización o daños de los datos, programas o documentos electrónicos pertenecientes a Properati y/o a terceros, así como de introducir o difundir en la Red “programas”, “virus”, “applets”, “controles Active X” o cualquier instrumento o dispositivo físico o electrónico que causen o sean susceptibles de causar cualquier tipo de alteración en la Red, en el sistema, o en los equipos de terceros. Igualmente, queda expresamente prohibida cualquier tipo de actividad o práctica que transgreda los principios de buena conducta aceptados generalmente entre los Usuarios de Internet.
    
    Asimismo quien realice actividades prohibidas por los presentes Términos y Condiciones será penal y económicamente responsable por los daños producidos.
    
    El Usuario reconoce que el Administrador puede poner límites respecto al uso del Servicio, con inclusión, entre otras cosas, de la cantidad máxima de días que el Contenido será retenido por el Servicio, la cantidad y el tamaño máximo de los anuncios, los mensajes de email, o de todo otro Contenido que se puede transmitir o almacenar a través del Servicio, y la frecuencia con la cual el Usuario puede acceder al Servicio. El Usuario conviene en que el Administrador no es responsable de la eliminación o el fracaso en el almacenamiento de aquel Contenido que se conserva o que se transmite a través del Servicio. El Usuario entiende que el Administrador se reserva el derecho para, en todo momento, modificar o interrumpir el Servicio (o una parte de este) con o sin notificación, y que el Administrador no será responsable ante el Usuario ni ante un tercero por la modificación, la suspensión o la interrupción del Servicio. El Usuario conviene en que el Administrador a su entera y sola discreción, tiene el derecho (pero no la obligación) de eliminar o desactivar la cuenta del Usuario, de bloquear su dirección de email o IP, o bien de cualquier otra forma cancelar el acceso o el uso del Servicio (o parte de este) por parte del Usuario, en forma inmediata y sin notificación previa. Asimismo, el Administrador podrá quitar o descartar Contenido dentro el Servicio, por cualquier motivo, con inclusión, no restrictiva, del momento en que el Administrador considere que el Usuario actuó en forma contraria a la letra o el espíritu de las Condiciones. Sumado a ello, el Usuario conviene en que el Administrador no será responsable ante el Usuario mismo ni ante un tercero por la cancelación del acceso del Usuario al Servicio. Además, el Usuario conviene en no intentar usar el Servicio luego de la cancelación.
    
</p>    

    POLÍTICAS DE PRIVACIDAD: PROTECCIÓN DE DATOS PERSONALES
<p>    
Properati solo recolecta datos personales que el Usuario nos envía en forma voluntaria y con una finalidad específica. El Usuario puede brindarnos datos como forma de registración para algún servicio, o al realizar llamados o consultas por teléfono o cualquier otro medio de comunicación.

Los datos serán usados para que el Usuario de Internet, que publique información en el sitio de Properati, pueda ser contactado por el interesado en adquirir bienes o servicios relacionados a la información publicada o para que aquel interesado sea contactado por dicho oferente.

Asimismo, los datos podrán ser usados para que Properati contacte a los Usuarios a fin de brindarle información sobre cambios y/o novedades y/o requerirles información sobre la experiencia en el uso del sitio web. Sus datos podrán ser compartidos con otras empresas subsidiarias o afiliadas de Properati

Esos datos no serán usados con otra finalidad distinta que aquella para la que fueron recolectados en cada oportunidad, excepto en el caso que sea requerido de otro modo por la ley. No se requiere que el Usuario proporcione información personal sensible como condición para usar este Sitio, a menos que sea necesario para proveer información adicional que el Usuario solicite. Cuando el Usuario utiliza este Sitio, almacenamos datos en nuestros servidores para posibilitar la conexión y por cuestiones de seguridad. Estos datos pueden incluir el nombre de su proveedor de servicio de Internet, el sitio web que el Usuario ha usado para vincularse a este Sitio, los sitios web de Properati que el Usuario ha visitado, los sitios web que el Usuario visita desde nuestro este Sitio, su dirección IP (Internet Protocol), la fecha y duración de sus visitas a este Sitio. Estos datos podrían conducir posiblemente a su identificación, pero generalmente no lo hacemos. Utilizamos los datos periódicamente para fines estadísticos, pero mantenemos el anonimato de cada usuario individual de manera tal que la persona no pueda ser identificada. Los datos personales se reúnen exclusivamente si el Usuario nos los proporciona, a través del registro, del llenado de formularios o de correos electrónicos, como parte de un pedido de mayor información, de consultas o solicitudes acerca de este Sitio y situaciones similares en las que el Usuario haya elegido proveernos esa información.

Mantendremos el control de y la responsabilidad del uso de cualquier dato personal que el Usuario nos proporcione y solo los usaremos para contactarlo por vía electrónico o telefónica. Algunos o todos estos datos pueden ser almacenados o procesados en ordenadores ubicados en otras jurisdicciones, cuyas leyes de protección de la información pueden diferir de la jurisdicción del domicilio del Usuario. Los datos del Usuario podrán ser compartidos con terceras partes, así como con otras empresas subsidiarias o afiliadas de El Administrador. Si la totalidad de los activos del Administrador son vendidos o fusionados con otra compañía, la sociedad adquirente podrá acceder a la información personal del Usuario sin su consentimiento. Si una parte del negocio de Properati es vendido, la entidad adquirente deberá tener acceso a la información personal del Usuario sin su consentimiento. En caso de que el Usuario utilice los medios de comunicación de mensajes provistos por Properati, El Administrador podrá almacenar y acceder a dichos mensajes, hacer un seguimiento y remitir notificaciones relacionadas a dicho mensaje.

ALMACENAMIENTO DE DATOS
Los datos personales que el Usuario pudiera haber brindado a Properati serán almacenados durante el tiempo requerido para la finalidad para la cual pudieran haber sido solicitados por Properati o brindados por el Usuario. Esos datos se utilizarán únicamente con el propósito de proporcionarle la información o evacuar la consulta que el Usuario haya requerido o para otros propósitos para los cuales el Usuario dio su consentimiento, salvo que la ley estipule otra cosa.

DERECHO DE ACCESO, RECTIFICACIÓN Y SUPRESIÓN
El Usuario como titular de los datos personales tiene la facultad de ejercer el derecho de acceso a los mismos en forma gratuita a intervalos no inferiores a seis meses, salvo que acredite un interés legítimo al efecto. Asimismo, el Usuario tiene derecho a corregir los datos personales inexactos y a retirar el consentimiento que ha dado para su utilización al Administrador solicitando que los mismos sean eliminados de los registros en los cuales se encuentren almacenados. Para acceder a sus datos personales por favor comuníquese con nuestro Oficial de Privacidad y Protección de Datos Personales a través del correo electrónico privacy@properati.com. En dichas solicitudes el titular del dato deberá, en todo caso, previamente acreditar identidad acompañando copia de documento nacional de identidad.

SEGURIDAD
Properati es consciente de la importancia que tienen para el Usuario la confidencialidad y seguridad de sus datos personales generados por el uso de este Sitio. Para ello, adoptamos precauciones de seguridad técnicas y de organización a fin de proteger sus datos personales de manipulación, pérdida, destrucción o acceso por personas no autorizadas. Nuestros procedimientos de seguridad experimentan revisiones continuas basadas en el desarrollo de nuevas tecnologías.


</p>
</body>
</html>